
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 04 10:40:58 CST 2024
//----------------------------------------------------

package calculadora;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUBLICO = 24;
  public static final int CHAR = 27;
  public static final int ENTERO = 25;
  public static final int CASE = 19;
  public static final int DOUBLE = 26;
  public static final int FOR = 17;
  public static final int STATIC = 33;
  public static final int SOUT = 37;
  public static final int PRIVADO = 23;
  public static final int IGUAL = 12;
  public static final int DOS_P = 21;
  public static final int CLASS = 30;
  public static final int NUM = 9;
  public static final int MAIN = 35;
  public static final int IF = 2;
  public static final int ID = 7;
  public static final int EOF = 0;
  public static final int COMILLA = 36;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int MENOS = 16;
  public static final int COR = 31;
  public static final int BREAK = 22;
  public static final int VOID = 28;
  public static final int COMILLASIM = 38;
  public static final int SWITCH = 18;
  public static final int ELSE = 13;
  public static final int WHILE = 14;
  public static final int DEFAULT = 20;
  public static final int PARC = 4;
  public static final int STRING = 34;
  public static final int PARA = 3;
  public static final int OPR = 8;
  public static final int PUNYCOM = 11;
  public static final int CORA = 32;
  public static final int LLAVEC = 6;
  public static final int LLAVEA = 5;
  public static final int DO = 15;
  public static final int MAS = 10;
}

