/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import java.io.StringReader;
import tablaDispersion.TablaHash;

/**
 *
 * @author Intel
 */
public class VentanaEstructuraCLASS extends javax.swing.JFrame {

    private static String res = "";
    public static int contador = 0;
    public static int contadorV = 0;
    public static int contadorChar = 0;
    public static String unaCad = "";
    public static int contunaCadArray = 0;
    public static String[] unaCadArray = new String[1000];
    public static char vocal = '\u0000';
    public static char[] vocalx = new char[6];

    public static void setRes(String r) {
        res = r;
    }

    public static String getRes() {
        return res;
    }

    public static void agregarRes(String r) {
        res += r;
    }

    /**
     * Creates new form VentanaEstructuraCLASS
     */
    public VentanaEstructuraCLASS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taCodigoFuente = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taResultado = new javax.swing.JTextArea();
        btnResolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taCodigoFuente.setColumns(20);
        taCodigoFuente.setRows(5);
        taCodigoFuente.setText("public class HolaMundo {\n    public static void main(String[] args) {\n        System.out.println(\"Hola xd\");\n        System.out.println(\"Mundo\");\n        System.out.println(\"Jose\");\n        System.out.println(\"Ramon\");\n\n        System.out.println(\"Escriba una vocal minuscula (x para salir): \");\n            //char input = scanner.next().charAt(0);\n\n            switch (input) {\n                case 'a':\n                    System.out.println(\"\\n  Avion\\n\");\n                    break;\n                case 'e':\n                    System.out.println(\"\\n  Elefante\\n\");\n                    break;\n                case 'i':\n                    System.out.println(\"\\n  Iglesia\\n\");\n                    break;\n                case 'o':\n                    System.out.println(\"\\n  Oso\\n\");\n                    break;\n                case 'u':\n                    System.out.println(\"\\n  Uva\\n\");\n                    break;\n                case 'x':\n                    System.out.println(\"\\nPrograma terminado\\n\");\n                   break;\n                default:\n                    System.out.println(\"\\nOpcion no valida\\n\");\n                    break;\n            }\n        \n    }\n}\n");
        jScrollPane1.setViewportView(taCodigoFuente);

        taResultado.setColumns(20);
        taResultado.setRows(5);
        jScrollPane2.setViewportView(taResultado);

        btnResolver.setText("Resolver");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(btnResolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnResolver)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String codigoInicial() {
        String r = "; Lenguaje Ensamblador\n"
                + "; Jose Ramon Paredes Perez\n"
                + "; Programa que muestra como imprimir una cadena de\n"
                + "; caracteres en pantalla (int 21h, servicio 9h).\n"
                + "; La estructura del programa sigue la especificacion NASM\n"
                + "; NASM - Netwide Assembler\n"
                + "\n"
                + ".model small\n"
                + ".stack 100h\n"
                + "\n"
                + ".data\n\n";

        return r;
    }

    private String codigosemiFinal() {
        String r = "\n\n"
                + ".code\n"
                + "programa:\n"
                + "   MOV   AX,@data\n"
                + "   MOV   DS, AX\n"
                + "\n";

        return r;
    }

    private String codigoFinal() {
        String r = "\nsalirProg: \n"
                + "   mov   ah,9\n"
                + "   lea   dx,espacio\n"
                + "   int   21h\n"
                + "   \n"
                + "   mov   ah,9\n"
                + "   lea   dx,salir\n"
                + "   int   21h\n"
                + "   \n"
                + "   mov   ah,4ch\n"
                + "   mov   al,0  \n"
                + "   int   21h     \n"
                + "end programa";

        return r;
    }


    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed
        // José Ramón Paredes Pérez
        try {
            // Creamos un escáner para leer el código que escribimos
            AnalizadorLexico scanner = new AnalizadorLexico(new StringReader(taCodigoFuente.getText()));

            // Ahora creamos el parser que va a entender lo que leemos
            AnalizadorSintactico Parser = new AnalizadorSintactico(scanner);
            taResultado.setText("");
            // Limpiamos el resultado anterior
// José Ramón Paredes Pérez
            // Le decimos al parser que haga su chamba
            Parser.parse();
            for (int i = 0; i < unaCadArray.length; i++) {
                if (unaCadArray[i] != null) {
                    contunaCadArray++;
                }

            }

            res += codigoInicial();
            for (int i = 0; i < contador; i++) {
                res += "\ncadena" + (i + 1)
                        + "   db   \""
                        + unaCadArray[i]
                        + "\" "
                        + "10,13,10,13,\"$\"";

            }
            res += codigosemiFinal();
            for (int i = 0; i < contador; i++) {
                res
                        += // "   ; Servicio 9h\n"
                        // + "   ; [Imprimir una cadena apuntada por DS:DX]\n"
                        //+ "   ; [la cadena debe terminar con \"$\"]\n"
                        "   MOV    AH, 9 ; AH = 9h\n"
                        + "   LEA    DX, cadena" + (i + 1) + "\n"
                        // + "   ; Invocar interrupci?n 21h\n"
                        + "   INT    21h"
                        + "        \n\n";

                if (i == (contador - 6)) {
                    for (int j = (contador - 6); j < contunaCadArray; j++) {
                        res
                                += "   cmp  al,'" + (vocalx[contadorChar]) + "'\n"
                                + "   je   cadena" + j + "\n"
                                + "   \n"
                                + "   \n";
                        contadorChar++;
                    }
                    res += "   mov   ah,9\n"
                            + "   lea   dx,noValido\n"
                            + "   int   21h\n"
                            + "   ;****************\n"
                            + "   jmp  pedirCaracterECO";
                    contadorChar = 0;
                    for (int j = (contador - 6); j < contunaCadArray; j++) {
                        res += "   \n"
                                + "cadena" + j + "\n"
                                + "   mov   ah,9\n"
                                + "   lea   dx," + (vocalx[contadorChar]) + "'\n"
                                + "   int   21h\n"
                                + "   jmp   pedirCaracterECO\n"
                                + "\n";
                        contadorChar++;
                    }
                }

            }
            res += codigoFinal();
            res += "\n\n";
            // Mostramos el resultado en la pantalla
            taResultado.setText(res);

        } catch (java.io.FileNotFoundException e) {
            // Si no encuentra el archivo, nos avisa
            System.out.println("Eh men, no encuentro el archivo: \"" + "codigoFuente.txt" + "\"");

        } catch (java.io.IOException e) {
            // Si hay problemas leyendo el archivo, nos dice qué pasó
            System.out.println("Ups, algo salió mal leyendo \"" + "codigoFuente.txt" + "\"");
            System.out.println(e);

        } catch (Exception e) {
            // Si pasa algo raro que no esperábamos, también nos avisa
            System.out.println("Este es el error: " + e);
            System.out.println("Vaya, pasó algo que no esperabaa:");
        }
    }//GEN-LAST:event_btnResolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEstructuraCLASS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEstructuraCLASS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEstructuraCLASS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEstructuraCLASS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEstructuraCLASS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taCodigoFuente;
    private javax.swing.JTextArea taResultado;
    // End of variables declaration//GEN-END:variables
}
